# Generated by Django 3.2.3 on 2021-05-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
