# Generated by Django 3.2.3 on 2021-05-14 07:35

from django.db import migrations, models
import root.utils


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, upload_to=root.utils.customer_image_file_path),
        ),
    ]
