# Generated by Django 3.2.3 on 2021-05-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20210525_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='file_csv',
            field=models.FileField(null=True, upload_to='csv_files'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
