# Generated by Django 3.2.3 on 2021-05-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_csv_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='title',
        ),
    ]
